### ISSUE TITLE
autobot not working properly

### ISSUE THREAD

**Issue by 1-ARIjitS** [1-ARIjitS/chrome-dino-autobot#1]
the image grabbing and drawing perfect rectangle is going wrong. please help me out in making this a bug free code by including the code for the dino to avoid birds

**Comment by ddrm86** [comment]
Hi! Tell me if I understand the code: it is taking a screenshot of the whole desktop? I think it is more robust if we can get every time the actual image of the game screen using Beautiful Soup or something similar, and work with that. What do you think?

**Comment by Aliex-dev** [comment]
i think i  understood the problem in the code can you please assign this work to me

**Comment by 1-ARIjitS** [comment]
the issue is resolved do check the repo
